[OXFORD_ABSTRACTS]
# https://app.oxfordabstracts.com/new-graphql-api-key
api_key=REDACTED
# RSECon25
event_id=75166

[ZENODO]
# https://(sandbox.)zenodo.org/account/settings/applications/tokens/new/
# Note, Zenodo sandbox is a separate website, with separate accounts/communities/API keys
api_key=REDACTED
use_sandbox=TRUE
# All Zenodo API calls will instead just print the action to stdout
dry_run=FALSE
# Will only create draft records on Zenodo, rather than publishing which cannot be easily reverted
draft_only=FALSE
# If draft_only is true, this will ask for path to a file to use for all record uploads
fake_upload=FALSE
# If draft_only is false, this will search for files recurively in the specified directory
# (Note, I was unable to download an archive of the directory from drive.google.com it returned an error.
#  This path is google drive filestream, where I had added a shortcut to my personal drive)
file_search_root=G:\.shortcut-targets-by-id\1DE3FekzYg4SbWw2rm5XZmx3zXG7QsVib\RSECon25\Programme\Material\Final Material (for conf week)
# glob style (fnmatch) case-insensitive blacklist of filenames to ignore
file_blacklist=
  desktop.ini
  *transcript.txt
  *.gslides
  *.gdoc
# Zenodo keywords to tag all records with
keywords=
  rse
# Zenodo commumities to attach records to
community_identifiers=
  rsecon25test3
  rse
# Submission IDs to be skipped
skipped_submissions=
  # Junk Value
  0
# CSV containing mapping of Submission id to YouTube URL
youtube_csv=rsecon25-youtube.csv
youtube_csv_id=oa_serial
youtube_csv_url=youtube_url
# Static conference information to be entered into every created record
# https://developers.zenodo.org/#representation
conference_title=RSE Conference 2025
conference_acronym=RSECon25
conference_dates=9-11 September 2025
conference_place=Warwick, UK
conference_url=https://rsecon25.society-rse.org/